kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: docker-registry.35.202.15.36.nip.io/go-auth
      registry: docker-registry.35.202.15.36.nip.io
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
