kind: pipeline
name: go-auth

clone:
  depth: 1

steps:
  - name: test
    image: golang:1.12
    commands:
      - go get -u github.com/kalderasoft/go-auth
      - cd $GOPATH/src/github.com/kalderasoft/go-auth
      - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - dep ensure
      - go test
  - name: tag
    image: alpine:3.7
    commands:
      - echo $DRONE_COMMIT > .tags
      - cat .tags
  - name: docker
    image: plugins/docker
    settings:
      repo: docker-registry.35.202.15.36.nip.io/go-auth
      registry: docker-registry.35.202.15.36.nip.io
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
  - name: deploy
    image: quay.io/honestbee/drone-kubernetes
    settings:
      kubernetes_server: https://35.225.64.169
      kubernetes_token:
        from_secret: k8s_admin_token
      namespace: auth-server
      deployment: authserver
      repo: docker-registry.35.202.15.36.nip.io/go-auth
      container: authserver
      tag: ${DRONE_COMMIT_SHA}
#  - name: notify
#    image: drillster/drone-email
#    settings:
#      host: smtp.gmail.com
#      username:
#        from_secret: gmail_username
#      password:
#        from_secret: gmail_password
#      from:
#        from_secret: gmail_from
#      skip_verify: true
#      recipients: [ erkanzileli@gmail.com ]
#      recipients_only: true
